//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongNo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongNo()
        {
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public int IDCongNo { get; set; }
        public Nullable<int> IDQuy { get; set; }
        public string MucDich { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<double> LaiSuat { get; set; }
        public string MaSoThue { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public string Note { get; set; }
        public string MaCongNo { get; set; }
        public Nullable<byte> State { get; set; }
        public Nullable<int> IDKhoanVay { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<decimal> Payed { get; set; }
        public Nullable<decimal> ConNo { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
        public virtual Quy Quy { get; set; }
    }
}
