//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTTamUng
    {
        public int IDCTTamUng { get; set; }
        public Nullable<int> IDTamUng { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<byte> State { get; set; }
        public string Note { get; set; }
    
        public virtual TamUng TamUng { get; set; }
    }
}
