//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TamUng
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TamUng()
        {
            this.CTTamUngs = new HashSet<CTTamUng>();
        }
    
        public int IDTamUng { get; set; }
        public string MST { get; set; }
        public Nullable<decimal> SoTienDaUng { get; set; }
        public Nullable<System.DateTime> HanThanhToan { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public string Note { get; set; }
        public Nullable<int> IDQuy { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string MaTamUng { get; set; }
        public Nullable<byte> State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTamUng> CTTamUngs { get; set; }
        public virtual Quy Quy { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
