//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuChi
    {
        public int IDThuChi { get; set; }
        public Nullable<int> IDQuy { get; set; }
        public string MucDich { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public string Note { get; set; }
        public string MaThuChi { get; set; }
        public Nullable<byte> State { get; set; }
    
        public virtual Quy Quy { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
